# Generated by Django 5.0.2 on 2024-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('reference_value', models.CharField(max_length=100)),
            ],
        ),
    ]
