# Generated by Django 5.0.2 on 2024-04-06 13:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labtest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_received_date', models.DateField()),
                ('referenced_by', models.CharField(max_length=255)),
                ('report_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labreport.labreport')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtest.labtest')),
            ],
        ),
    ]
